### ISSUE TITLE
Clarity in install documentation

### ISSUE THREAD

**Issue by ksnyde** [runspired/flexi#39]
In the installation section of the documentation you state:

> ![image](https://cloud.githubusercontent.com/assets/980757/14182876/4e637026-f765-11e5-9c8f-acfd3a67bdd8.png)

Does this mean that traditional apps (aka., non-pod) should also include `pod-templates-shim`?

**Comment by ksnyde** [comment]
If yes, then I think it would make sense to rename it to remove cognitive friction but I guess an explicit note in the documentation would help too.

**Comment by runspired** [comment]
Correct, this shim is only needed for pod templates.

**Comment by ksnyde** [comment]
Ahhh. Ok then just a documentation update I guess. How are you building your documentation system? I'm happy to send a PR in for some of the documentation changes if that's helpful (also happy to just raise issues). Up to you.

**Comment by runspired** [comment]
All of the documentation is here, it's an ember-app running within this repo:

https://github.com/runspired/flexi/tree/develop/tests/dummy/app/routes/docs
