### ISSUE TITLE
Error: Import directives may not be used within control directives or mixins.

### ISSUE THREAD

**Issue by maxkwallace** [runspired/flexi#52]
There's been some discussion on https://embercommunity.slack.com/messages/e-flexi/ but I thought it was worth opening an issue here, in case anyone looks here first.

As https://embercommunity.slack.com/messages/e-flexi/team/mellatone/ points out:

```
web/tmp/sass_compiler-input_base_path-inMk4ecM.tmp/0/addon.scss (4)
The Broccoli Plugin: [SassCompiler] failed with:
Error: Import directives may not be used within control directives or mixins.
```

The issue appears to be coming from

 ```
@if ($include-css) {
  @import 'mixins/index';
  @import 'grid/grid';
  @import 'helpers/index';
  @import 'components/index';
}
```

in `flexi/addon/styles/addon.scss`.

**Comment by maxkwallace** [comment]
I commented out the `@if ($include-css) {` above, and one other `@if ...` in Flexi, and pushed that to: https://github.com/shearwater-intl/flexi

The issue above appears to be fixed for me once I point my Flexi dependence to that repo:

```
    "flexi": "git://github.com/shearwater-intl/flexi.git#5d8fb70cad561042ffad7a06d45c744fe203c881",
```

**Comment by max** [comment]
You can also downgrade `"node-sass": "3.4.1"`.

**Comment by runspired** [comment]
Fixed in more recent releases.
