### ISSUE TITLE
Fastboot?

### ISSUE THREAD

**Issue by bgentry** [runspired/flexi#58]
First, thanks for the great project! 👍 

My question is whether you have given any thought to how Flexi might work with Fastboot. My understanding is that it would have to render the DOM based only on the info from the browser's request, and that Flexi would have to select a specific breakpoint to render. I guess Flexi could attempt to do that based on the user agent.

Is that the best that could be done? Maybe something with [HTTP Client Hints](http://httpwg.org/http-extensions/client-hints.html) if those get adopted more widely than just Chrome? Do you have any current plans to work on Fastboot compatibility?

**Comment by runspired** [comment]
Fastboot is supported, all you need is an initialized specific to fastboot that looks up the service and sets the desired device width

**Comment by dustinfarris** [comment]
When I run `ember fastboot --serve-assets`  and then visit the site, I get:

```
There was an error running your app in fastboot. More info about the error:
 TypeError: window.addEventListener is not a function
    at setupResize (/Users/dustin/Developer/industrymaps-web/dist/fastboot/vendor.js:100252:14)
```

Seems to be referring to this method: https://github.com/runspired/flexi/blob/develop/addon/services/device/layout.js#L51

**Comment by jasonmit** [comment]
This should be fixed on master

**Comment by dustinfarris** [comment]
@runspired possible to have a patch release with this fix?

**Comment by rwwagner90** [comment]
+1 still seeing this error with Fastboot

**Comment by runspired** [comment]
Should be fixed on master, releasing master in a moment.  If release did not fix please ping and I'll reopen.  I need a fastboot testing env.
