### ISSUE TITLE
acceptance tests using Flexi take > 5 seconds

### ISSUE THREAD

**Issue by bgentry** [runspired/flexi#60]
After switching some of my app to Flexi, I noticed that some acceptance tests were stalling for 5 seconds. The same thing also happens when running Flexi's own acceptance tests:

<img width="1407" alt="screen shot 2016-05-22 at 5 12 43 pm" src="https://cloud.githubusercontent.com/assets/114033/15457568/8c260c6c-2040-11e6-846b-d728c439e432.png">

It looks like this is caused by the [`DEFAULT_EXPIRES`](https://github.com/runspired/flexi/blob/54f1ad30435b810a5d640feac63a661b051913c3/addon/lib/sustain.js#L10) setting, because if I pass `expires=1000` to my `sustain` invocation, the stall time drops to 1 second.

**Comment by runspired** [comment]
@bgentry I'll add an `is-in-test` test to the default value for expires and set it to something more reasonable for tests.

**Comment by runspired** [comment]
Fixed on master :)
