### ISSUE TITLE
-webkit-box-flex should only take one parameter

### ISSUE THREAD

**Issue by kybishop** [runspired/flexi#78]
As per https://developer.mozilla.org/en-US/docs/Web/CSS/box-flex, `-webkit-box-flex` only takes one parameter, though it is currently passed what would normally be used for the `flex` property.

**Comment by runspired** [comment]
PR welcome, I won't have much time for this for a few more weeks, but I'm going to do a patch release tomorrow so if you can squeeze it in before then :D
