### ISSUE TITLE
emails sample not working

### ISSUE THREAD

**Issue by kmichek** [runspired/flexi#82]
Hello, I've tried to build the "email client" sample, unfortunately it blows up in sustain.js: 
// if the component hasn't explicitly set it's layout, look it up
// pre Ember 2.0, layout is a computed property that MUST be set
// via get/set
if (!this._component.get('layout'))
I am Ember novice, probably missed some basic assumption of the sample. Would you please help me?. I'm eagerly waiting for a demo source code. Thank you. Karel

**Comment by runspired** [comment]
The entire docs site is built in flexi and available in the dummy app source.
