### ISSUE TITLE
plugin that does not provide a caching strategy

### ISSUE THREAD

**Issue by nomeacuerdo** [runspired/flexi#83]
After installing, running `ember build` i get the following errors:
> DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-attribute-conversion`.
DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-component-conversion`.
DEPRECATION: ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-sustain-conversion`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-attribute-conversion`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-component-conversion`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-sustain-conversion`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-attribute-conversion`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-component-conversion`.
DEPRECATION: ember-cli-htmlbars is opting out of caching due to an AST plugin that does not provide a caching strategy: `flexi-sustain-conversion`.

and sometimes Segmentation fault: 11.

According to this issue: https://github.com/runspired/flexi/pull/79 it should be fixed bi adding the `baseDir`, but after doing that it always throws Segmentation fault: 11.

`ember -v`: 
ember-cli: 2.7.0
node: 5.5.0
os: darwin x64

Thanks for the help, and congrats for the module, it looks awesome!

**Comment by runspired** [comment]
Fixed on master.
